# -*- coding: utf-8 -*-
"""Solubility-Prediction-Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ESRYKo7sGTawkf7EhCUE8dZxFJcelJAK

# **Git Configuration**

# **Load Data**
"""

import pandas as pd

df=pd.read_csv('https://raw.githubusercontent.com/azwar-m/datasets/refs/heads/main/delaney_solubility_with_descriptors.csv')
df
print("Dataset Downloaded")

print(df.shape)

"""# **Data Preparation**

##  **Data Separation as X and Y**
"""

x=df.drop('logS',axis=1)
x

y=df['logS']
y

"""## **Splitting Data**"""

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=100)

x_train

x_test

y_train

y_test

"""# **Model Building**

## **Linear Regression**

### **Training the Model**
"""

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train, y_train)
print("Model Trained")

"""### **Making Prediction**"""

y_lr_train_pred = lr.predict(x_train)
y_lr_test_pred = lr.predict(x_test)

y_lr_train_pred

y_lr_test_pred

"""### **Performance Evaluation**"""

from sklearn.metrics import mean_squared_error, r2_score

lr_train_mse = mean_squared_error(y_train, y_lr_train_pred)
lr_train_r2 = r2_score(y_train, y_lr_train_pred)
lr_test_mse = mean_squared_error(y_test, y_lr_test_pred)
lr_test_R2 = r2_score(y_test, y_lr_test_pred)

lr_prediction = pd.DataFrame(['Linear Regression',lr_train_mse, lr_train_r2, lr_test_mse, lr_test_R2]).transpose()
lr_prediction.columns = ['Model', 'Training MSE', 'Training R2', 'Test MSE', 'Test R2']
print("Performance Evaluated")
lr_prediction
print(lr_prediction)
